### ISSUE TITLE
Section 4

### ISSUE THREAD

**Issue by mfortini** [ietf-wg-httpapi/ratelimit-headers#39] opened 2021-03-15 11:59 UTC
https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#name-providing-ratelimit-fields

You state _‘A server MAY use one or more "RateLimit" response fields defined in this document to communicate its quota policies.’_ but it does not clearly define how they would be used in isolation or how a client should respond to a limited set of headers (other than discussed earlier above)

My feeling is  RateLimit-Limit can be optional and RateLimit-Remaining and RateLimit-Reset can be used as a pair. RateLimit-Reset would only have value in isolation if sent with a 429 response code, on other responses it would be meaningless.

(Erik de Kok, Mimecast)

**Comment by ioggstream** [comment] 2021-03-16 08:41
Duplicate of #11

**Closed by ioggstream** 2021-03-16 08:41 UTC
